#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
