#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
