#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
file=/var/run/myscript.pid

echo $$ > $file

#Displays I hate the kill command when receiving a SIGTERM signal
trap 'echo I hate the kill command ; sudo rm '"$file"' ; exit' SIGTERM

#Displays Y U no love me?! when receiving a SIGINT signal
trap 'echo Y U no love me?!' SIGINT

#Deletes the file /var/run/myscript.pid and terminates itself
trap 'sudo rm '"$file"' ; exit' SIGQUIT

#Displays To infinity and beyond indefinitely
while true
do
    echo "To infinity and beyond"
done
