#!/usr/bin/env bash
# manages 'manage_my_process'
# argument 'start' starts the process, creates a file containing PID, displays message
# argument 'stop' stops process, deletes file, displays message
# argument 'restart' stops process, deletes file, starts process, creates new file, displays message

case "$1" in
start)
	./manage_my_process &
	echo "$!" >/var/run/my_process.pid
	echo "manage_my_process started"
	;;
stop)
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
restart)
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" >/var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
