#!/usr/bin/env bash
#Displays "Best Schhol" 10 times but adds "Hi" on 9th iteration

var="Best School"
i=1

while [ "$i" -le 10 ];
do
	echo "$var"
	if [ "$i" == 9 ]; then
		echo "Hi"
	fi
	((i += 1))
done
