#!/usr/bin/env bash
#Displays "bad luck" on 4th, "good luck" on 8th and "Best School"

var="Best School"
i=1

while [ "$i" -le 10 ];
do
	if [ "$i" == 4 ]; then
		echo "bad luck"
	elif [ "$i" == 8 ]; then
		echo "good luck"
	else
		echo "$var"
	fi
	((i += 1))
done
