#!/usr/bin/env bash
#Displays hour 0-12 and minutes 1-59

hour=0
minutes=1

while [ "$hour" -le 12 ];
do
	echo "Hour: $hour"
	minutes=1
	while [ "$minutes" -le 59 ];
	do
		echo "$minutes"
		((minutes += 1))
	done
	((hour += 1))
done
