#!/usr/bin/env bash
# Configures an ubuntu server with the below requirements

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >>~/hosts.new
cp -f ~/hosts.new /etc/hosts
